name: Address Services CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt

      - name: Test with pytest
        run: |
          pytest

      - name: Login to DockerHub
        # uses: docker/login-action@v2
        # env:
        #   DOCKER_USERNAME: 
        #   DOCKER_TOKEN: ${{ env.DOCKER_TOKEN }}
        run: |
          echo "teste"
          echo "dckr_pat_5IBayN9UvXHQUhScwJ-XPQP47mc" | docker login -u "thomasmichelsbnu" --password-stdin

      - name: Build, tag
        env:
          CONTAINER_NAME: ${{ env.MY_CONTAINER_NAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t address-services:$IMAGE_TAG .

      - name: Push
        run: |
          docker push $DOCKER_USERNAME/$CONTAINER_NAME:latest
 