name: Address Services CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  CONTAINER_NAME: MY_CONTAINER_NAME
  IMAGE_TAG: github.sha
  DOCKER_USERNAME: DOCKER_USERNAME
  DOCKER_PASSWORD: DOCKER_PASSWORD

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt

      - name: Test with pytest
        run: |
          pytest

      - name: Login to DockerHub
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build, tag
        run: |
          docker build -t $CONTAINER_NAME:$IMAGE_TAG .

      - name: Push
        run: |
          docker push $CONTAINER_NAME:$IMAGE_TAG
